name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    if: false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.10", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv pip install --system --editable .[test]

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings
